# Generated by Django 5.2.7 on 2025-10-22 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=2)),
            ],
            options={
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("zip", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("token", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("shippo", "Shippo"),
                            ("shipshap", "Shipshap"),
                            ("dhl", "DHL"),
                            ("usps", "USPS"),
                            ("fedex", "FedEx"),
                            ("ups", "UPS"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "transaction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("eta", models.DateTimeField(blank=True, null=True)),
                ("original_eta", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.TextField(blank=True)),
                ("test", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments_from",
                        to="tracking.address",
                    ),
                ),
                (
                    "address_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments_to",
                        to="tracking.address",
                    ),
                ),
                (
                    "servicelevel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracking.servicelevel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("PRE_TRANSIT", "Pre-Transit"),
                            ("TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("RETURNED", "Returned"),
                            ("FAILURE", "Failure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status_date", models.DateTimeField()),
                ("status_details", models.TextField()),
                ("object_id", models.CharField(max_length=100)),
                ("object_created", models.DateTimeField()),
                ("object_updated", models.DateTimeField()),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracking.location",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="tracking.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-status_date"],
            },
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["tracking_number", "carrier"],
                name="tracking_sh_trackin_2d440c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trackingevent",
            index=models.Index(
                fields=["shipment", "-status_date"],
                name="tracking_tr_shipmen_e945ab_idx",
            ),
        ),
    ]
