# Generated by Django 5.2.7 on 2025-10-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="address_from",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="address_to",
        ),
        migrations.RemoveField(
            model_name="trackingevent",
            name="location",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="servicelevel",
        ),
        migrations.RemoveIndex(
            model_name="shipment",
            name="tracking_sh_trackin_2d440c_idx",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="carrier",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="eta",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="original_eta",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="test",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="transaction",
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="location_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="location_country",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="location_state",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="location_zip",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="ServiceLevel",
        ),
    ]
