# Generated by Django 5.2.7 on 2025-10-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_remove_shipment_address_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="tracking_number",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
