# Generated by Django 5.2.7 on 2025-10-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_alter_shipment_tracking_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackingevent",
            name="location_city",
        ),
        migrations.RemoveField(
            model_name="trackingevent",
            name="location_country",
        ),
        migrations.RemoveField(
            model_name="trackingevent",
            name="location_state",
        ),
        migrations.RemoveField(
            model_name="trackingevent",
            name="location_zip",
        ),
    ]
